<a href="https://colab.research.google.com/github/SangBeom-Hahn/BOAZ/blob/main/machineLearningCodeImplement1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 공부 방법
책에는 클래스 안에 완성 코드가 있다
코드 구현을 따라할 때 클래스랑 함수 다 벗기고 안에 코드 먼저 self 이런거 다 빼고 매개변수로 받은 것도 상수로 바꿔서 돌려본다
그 후에 클래스랑 함수로 다시 모은다

# 2.1 인공 뉴런 : 초기 머신 러닝의 간단한 역사

- 퍼셉트론 : 입력이 음수면 -1, 양수면 1

- 문제점 : 선형으로 구분 못하는 문제는 불가능

### 퍼셉트론 구현

In [ ]:
import numpy as np

In [ ]:
# 퍼셉트론 구현

import numpy as np

# 매개변수 1. 학습률, 2. 훈련 반복 횟수 -> 여러번 w를 조정, 3 random_state 난수 발생기 : 실행할 때마다 똑같은 난수를 만들기 위한 것(결과값이 똑같이 나오도록 재현하기 위한 것으로 실전에서는 절대 사용 안함)

class Perceptron():
  def __init__(self, eta=0.01, n_iter=50, random_state=1) # 생성자에 매개변수를 넣어서 퍼셉트론이 처음 만들어지면 매개변수를 받도록 만듬
    self.eta = eta # self 키워드로 객체 내의 변수로 3개의 값을 조작하기 위함 -> self가 멤버 변수로 만드는 느낌인가??
    self.n_iter = n_iter
    self.random_state = random_state

  def fit(self, X, y) # 모델을 훈련하는 메소드 
  # 매개변수 : 입력 x : 훈련데이터 2차원 배열(행과 feature 열), y : 타겟값 1차원 배열

    rgen = np.random.RandomState(self.random_state) # 난수 발생기를 초기화
    rgen.normal(loc=0.0, scale=0.01, size=1+X.shape[1]) # 0에서 1사이의 표준 편차가 0.01인 난수를 발생함 + 발생하는 개수는 특성 개수보다 하나 더 많게 발생함 왜? 절편 생각



















In [ ]:
# X를 엑셀이라고 보면 한 번에 111 한 행만 들어와서 x1, x2, x3가 되고 난수는 w로 w1, w2, w3인데 세타도 있으니 4개를 만든다.

def net_input(X):
  return np.dot(X, w_[1:]) + w_[0] # 입력을 wx 점곱을 하는 함수

def predict(X):
  return np.where(net_input(X) >= 0.0, 1, -1) # wx가 0보다 크면 1아니면 -1 = 결정함수를 통과한 값을 출력

X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
y = np.array([1,1,1])

rgen = np.random.RandomState(42) # 난수 발생기를 초기화
w_ = rgen.normal(loc=0.0, scale=0.01, size=1+X.shape[1])

errors1 = [] # 오차값을 출력하기 위한 빈 리스트

for _ in range(1000): # 반복 횟수만큼 훈련과정 반복
   errors = 0
   for xi, target in zip(X, y): #zip함수 인자를 X, y를 튜플로 만듬  
     print(xi, target)
     update = 0.01 * (target - predict(xi)) #xi를 예측함수에 넣어서 y햇을 만듬 > y햇을 타겟과 빼서 학습률을 곱해서 업데이트할 정도를 만듬
     w_[1:] += update * xi # 업뎃값에 xi를 곱해서 w를 업데이트를 함
     w_[0] += update # 절편은 그냥 업데이트 값으로만 업데이트 함 x0는 1이므로 곱하나 마나이다. update * (x0)1
     errors += int(update != 0.0) # 업데이트 값을 정확히 맞추지 못한 것을 에러라고 판단하여 카운트 증가 -> 바르게 예측했을 경우 빼면 0이 나와서 업데이트가 무조건 0이므로 != 0으로 한다,
   errors1.append(errors) # 에포크 마다 에러값을 리스트에 추가

print(errors1)

[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
[4 5 6] 1
[7 8 9] 1
[1 2 3] 1
